import React, { useState, useMemo } from 'react';
import CVUploader from './components/CVUploader';
import Hero from './components/Hero';
import Experience from './components/Experience';
import Projects from './components/Projects';
import Skills from './components/Skills';
import Education from './components/Education';
import Contact from './components/Contact';
import ScrollReveal from './components/ScrollReveal';
import { CVData, SectionType } from './types';

function App() {
  const [cvData, setCvData] = useState<CVData | null>(null);

  // Dynamic Section Ordering Logic
  const sections = useMemo(() => {
    if (!cvData) return [];

    const order: { type: SectionType; component: React.ReactNode; score: number }[] = [];

    // Always Hero first
    order.push({ 
      type: SectionType.HERO, 
      component: <ScrollReveal key="hero"><Hero data={cvData} /></ScrollReveal>, 
      score: 1000 
    });

    // Scoring logic
    const expCount = cvData.experience?.length || 0;
    const projCount = cvData.projects?.length || 0;
    const eduCount = cvData.education?.length || 0;

    // Experience: Higher priority if more than 2 jobs
    order.push({
      type: SectionType.EXPERIENCE,
      component: <ScrollReveal key="exp"><Experience data={cvData} /></ScrollReveal>,
      score: expCount > 0 ? 50 + (expCount * 5) : 0
    });

    // Projects: Boost score if projects exist, heavily boost if experience is low
    let projScore = projCount > 0 ? 45 + (projCount * 6) : 0;
    if (expCount < 2 && projCount > 0) projScore += 20; // Boost projects for juniors

    order.push({
      type: SectionType.PROJECTS,
      component: <ScrollReveal key="proj"><Projects data={cvData} /></ScrollReveal>,
      score: projScore
    });

    // Skills: Standard priority
    order.push({
      type: SectionType.SKILLS,
      component: <ScrollReveal key="skills"><Skills data={cvData} /></ScrollReveal>,
      score: 40
    });

    // Education: Lower priority generally, unless very little experience
    let eduScore = 20;
    if (expCount === 0) eduScore += 50; // Boost for fresh grads

    order.push({
      type: SectionType.EDUCATION,
      component: <ScrollReveal key="edu"><Education data={cvData} /></ScrollReveal>,
      score: eduScore
    });
    
    // Contact: Always last
    order.push({
      type: SectionType.CONTACT,
      component: <ScrollReveal key="contact"><Contact data={cvData} /></ScrollReveal>,
      score: -100
    });

    // Sort by score descending
    return order.sort((a, b) => b.score - a.score);
  }, [cvData]);

  if (!cvData) {
    return <CVUploader onDataParsed={setCvData} />;
  }

  return (
    <main className="min-h-screen bg-background text-textMain selection:bg-accent/30 selection:text-white">
      {/* Background ambient glow */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute -top-[20%] -right-[10%] w-[50%] h-[50%] rounded-full bg-accent/5 blur-[120px]"></div>
        <div className="absolute top-[20%] -left-[10%] w-[40%] h-[40%] rounded-full bg-purple-900/10 blur-[100px]"></div>
      </div>

      <div className="relative z-10">
        {/* Navigation/Header placeholder if needed, for now pure minimal */}
        
        <div className="flex flex-col gap-0 md:gap-12 pb-24">
          {sections.map((section) => section.component)}
        </div>

        <footer className="text-center py-12 text-textMuted text-sm border-t border-white/5">
          <p>Generated by AutoFolio using Gemini AI</p>
        </footer>
      </div>
    </main>
  );
}

export default App;